services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PYTHONPATH: /app/src
      POSTGRES_HOST: postgres
      REDIS_URL: redis://redis:6379/0
      OPENSEARCH_URL: http://opensearch:9200
      NEO4J_URI: bolt://neo4j:7687
      OPSGUARD_EVENT_BACKEND: jsonl
      OPSGUARD_GRAPH_BACKEND: memory
      OPSGUARD_RULE_SANDBOX: offline
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src:ro
      - ./datasets:/app/datasets:ro
      - ./knowledge:/app/knowledge:ro
      - ./reports:/app/reports

  postgres:
    profiles: ["adapters"]
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-opsguard}
      POSTGRES_USER: ${POSTGRES_USER:-opsguard}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change-me}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    profiles: ["adapters"]
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  opensearch:
    profiles: ["adapters"]
    image: opensearchproject/opensearch:2.16.0
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9200/_cluster/health >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 20

  neo4j:
    profiles: ["adapters"]
    image: neo4j:5-community
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-change-me}
      NEO4J_server_memory_heap_initial__size: 256m
      NEO4J_server_memory_heap_max__size: 512m
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  postgres_data:
  redis_data:
  opensearch_data:
  neo4j_data:
  neo4j_logs:
